### ISSUE TITLE
UI alignment issue on google review profile icon

### ISSUE THREAD

**Issue by ramnathkr** [d521bb85/react-elfsight-widget#1]
Using https://www.npmjs.com/package/react-elfsight-widget in Gatsby

UI alignment issue on google review profile icon
![Screenshot 2022-04-13 205221](https://user-images.githubusercontent.com/440285/163214760-eba9e9b1-6086-4d42-80f6-138744ad2703.jpg)

**Comment by welcomemax** [comment]
Hi @rmtsys

Perhaps you should contact to Elfsight Support - support@elfsight.com

This component does not apply to Google Reviews or any other widgets provided by Elfsight

But only provides a way to install a widget in a react application
